---
title: "Papers"
---

<style type="text/css">
.title {
  display: none;
}
ol li {
  margin-bottom: 8px;
}
</style>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Journal articles:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>**Ellis Cain** & Rachel Ryskin (Forthcoming in OpenMind). [Semantic Representations are Updated Across the Lifespan Reflecting Diachronic Language Change](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4883002).</li>

<li>**Ellis Cain**, Rachel Ryskin, & Chen Yu (2025). [Cross‐Situational Statistics Present in an Early Language Learning Context: Evidence From Naturalistic Parent–Child Interactions](https://escholarship.org/uc/item/3vq7v1s8). *Cognitive Science, 49(6)*, e70078.</li>

</ol>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Preprints:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>**Ellis Cain**, Elizabeth Geballe, & Tyler Marghetis (Preprint). [A literary translation cycle disentangles transmission pressures from sociocultural changes in cultural evolution](https://doi.org/10.31234/osf.io/9kvb4_v2).</li>

</ol>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Textbook Chapters:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>**Ellis Cain** & Jeff Yoshimi (2025). Word embeddings. [*Neural Networks for Cognitive Science.*](https://downloads.jeffyoshimi.net/NeuralNetworksCogsci.pdf)</li>

</ol>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Conference proceedings:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>Alton Chao, **Ellis Cain**, & Rachel Ryskin (2025). [Language experience and prediction across age groups: evidence from diachronic fine-tuning of language models](https://escholarship.org/uc/item/83b1p2nz). *In Proceedings of the Annual Meeting of the Cognitive Science Society* (Vol. 47, No. 47).</li>

<li>**Ellis Cain** & Rachel Ryskin (2024). [Diachronic change in verb usage statistics predicts differences in sentence processing across the lifespan](https://aclanthology.org/2024.cmcl-1.19.pdf). *In Proceedings of the Workshop on Cognitive Modeling and Computational Linguistics* (pp. 221-230).</li>

<li>**Ellis Cain** & Rachel Ryskin (2023). [Diachronic Language Change and Its Influence on Lexico-semantic Representations Across the Lifespan](https://escholarship.org/uc/item/943334rm). *In Proceedings of the Annual Meeting of the Cognitive Science Society* (Vol. 45, No. 45).</li>

<li>**Ellis Cain**, Rachel Ryskin, & Chen Yu (2022). [Quantifying cross-situational statistics during parent-child toy play](https://escholarship.org/uc/item/7w66j9bd). *In Proceedings of the Annual Meeting of the Cognitive Science Society* (Vol. 44, No. 44).</li>

<li>Yayun Zhang, **Ellis Cain**, David Crandall, & Chen Yu (2022). [Grounding Action Verbs in Egocentric Visual Perception](https://escholarship.org/uc/item/9h7090tp). *In Proceedings of the Annual Meeting of the Cognitive Science Society* (Vol. 44, No. 44).</li>

<li>Yayun Zhang, Andrei Amatuni, **Ellis Cain**, Xizi Wang, David Crandall, & Chen Yu (2021). [Human Learners Integrate Visual and Linguistic Information Cross-Situational Verb Learning](https://escholarship.org/uc/item/6gt5t65g). *In Proceedings of the Annual Meeting of the Cognitive Science Society* (Vol. 43, No. 43).</li>

<li>Yayun Zhang, Andrei Amatuni, **Ellis Cain**, & Chen Yu (2020). [Seeking Meaning: Examining a Cross-situational Solution to Learn Action Verbs Using Human Simulation Paradigm](https://cognitivesciencesociety.org/cogsci20/papers/0705/0705.pdf). *In Proceedings of the Annual Meeting of the Cognitive Science Society* (Vol. 42, No. 42).</li>
</ol>
