---
title: "Presentations"
---

<style type="text/css">
.title {
  display: none;
}
ol li {
  margin-bottom: 8px;
}
</style>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Invited talks:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>Alton Chao, **Ellis Cain**, & Rachel Ryskin (2025). Language experience and prediction across age groups: evidence from diachronic fine-tuning of language models. *For the MRPI Planning Grant: Leveraging California's Linguistic Diversity to Improve Large Language Models.* University of California</li>

</ol>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Talks:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>Alton Chao, **Ellis Cain**, & Rachel Ryskin (2025). Language experience and prediction across age groups: evidence from diachronic fine-tuning of language models. *At the California Meeting on Psycholinguistics (CAMP[8]).* Davis, CA</li>

<li>**Ellis Cain**, Alton Chao, & Rachel Ryskin (2024). Diachronic language change explains apparent age-related differences in information-theoretic efficiency. *At the Conference on Rational Approaches in Language Science (RAILS).* Saarbrucken, Germany</li>

<li>**Ellis Cain**, Alton Chao, & Rachel Ryskin (2024). Stability in the production of syntactic attachment across the lifespan. *At the California Meeting on Psycholinguistics (CAMP[7]).* San Diego, CA</li>

<li>**Ellis Cain**, & Rachel Ryskin (2024). Diachronic change in verb usage statistics predicts differences in sentence processing across the lifespan. *At the Workshop on Cognitive Modeling and Computational Linguistics.* Bangkok, Thailand</li>

<li>**Ellis Cain**, Brown-Schmidt, S., & Rachel Ryskin (2023). [Diachronic Verb Usage Statistics and Sentence Processing Across the Lifespan.](pdf/psychonomic_2023.pdf) *At the Annual Meeting of the Psychonomic Society.* San Francisco, CA</li>

<li>**Ellis Cain**, Rachel Ryskin, & Chen Yu (2022). [Quantifying cross-situational statistics during parent-child toy play.](pdf/cogsci_2022.pdf) *At the Annual Meeting of the Cognitive Science Society.* Toronto, Canada</li>

</ol>

<div class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 20px; padding-right: 20px; padding-left: 20px">
**Posters:**
</div>

<ol class="row" style="text-align: justify;  text-justify: inter-word; padding-top: 5px; padding-right: 20px; padding-left: 40px">

<li>Alton Chao, **Ellis Cain**, & Rachel Ryskin (2025). Language experience and prediction across the lifespan: evidence from diachronic fine-tuning of language models. *At the Annual Meeting of the Cognitive Science Society.* San Francisco, CA</li>

<li>**Ellis Cain**, Alton Chao, & Rachel Ryskin (2024). Diachronic language change explains apparent age-related differences in information-theoretic efficiency. *At the California Meeting on Psycholinguistics (CAMP[7]).* San Diego, CA</li>

<li>**Ellis Cain**, Elizabeth Geballe, & Tyler Marghetis. (2024). [Translation as Transmission: Disentangling the impact of cultural context from cultural transmission using an unusual English-to-English cycle of 19th century literary translations.](pdf/ces_2024.pdf) *At the Cultural Evolution Society Conference (CES).* Durham, UK</li>

<li>**Ellis Cain**, & Rachel Ryskin (2024). Neural Signatures of Language Processing Across the Lifespan. *At the Symposium of the Center for Interdisciplinary Neuroscience.* Merced, CA</li>

<li>**Ellis Cain**, & Rachel Ryskin (2023). [Diachronic Language Change and Its Influence on Lexico-semantic Representations Across the Lifespan.](pdf/cogsci_2023.pdf) *At the Annual Meeting of the Cognitive Science Society.* Sydney, AUS</li>

<li>**Ellis Cain** (2023). [Teaching An Old Dog New Tricks? Learning Rates, Aging, And Language Change.](pdf/cwess_2023.pdf) *At California Workshop on Evolutionary Social Science (CWESS).* Merced, CA</li>

<li>**Ellis Cain**, & Rachel Ryskin (2022). [Diachronic language change and meaning across the lifespan.](https://virtual.oxfordabstracts.com/#/event/3067/submission/166) *At Architectures and Mechanisms of Language Processing (AMLaP).* York, UK</li>

</ol>